import type { Metadata } from "next";
import { Livvic } from "next/font/google";
import "./globals.css";
import "react-multi-carousel/lib/styles.css";
import { ChakraProvider } from "@chakra-ui/react";

const inter = Livvic({
  subsets: ["latin"],
  weight: "700",
});

export const metadata: Metadata = {
  title: "Braintech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" title="Braintech">
      <body>
        <ChakraProvider>{children}</ChakraProvider>
      </body>
    </html>
  );
}
